version: '3.8'

services:
  # Redis for rate limiting
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  # API Gateway
  # api-gateway:
  #   build: .
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - DEBUG=False
  #     - REDIS_URL=redis://redis:6379/0
  #     - SECRET_KEY=${SECRET_KEY:-your-secret-key-here}
  #     - ALLOWED_HOSTS=localhost,127.0.0.1
  #     - USER_SERVICE_URL=${USER_SERVICE_URL:-http://localhost:8001}
  #     - PRODUCT_SERVICE_URL=${PRODUCT_SERVICE_URL:-http://localhost:8002}
  #     - ORDER_SERVICE_URL=${ORDER_SERVICE_URL:-http://localhost:8003}
  #   depends_on:
  #     - redis
  #   volumes:
  #     - ./logs:/app/logs
  #     - ./media:/app/media
  #   restart: unless-stopped
  #   command: >
  #     sh -c "python manage.py migrate &&
  #            python manage.py setup_gateway --all &&
  #            gunicorn api_gateway.wsgi:application --bind 0.0.0.0:8000 --workers 4"

  # Optional: Sample user service for testing
  user-service:
    image: nginx:alpine
    ports:
      - "8001:80"
    volumes:
      - ./sample_services/user_service.conf:/etc/nginx/conf.d/default.conf
      - ./sample_services/user_service:/usr/share/nginx/html
    restart: unless-stopped

  # Optional: Sample product service for testing
  product-service:
    image: nginx:alpine
    ports:
      - "8002:80"
    volumes:
      - ./sample_services/product_service.conf:/etc/nginx/conf.d/default.conf
      - ./sample_services/product_service:/usr/share/nginx/html
    restart: unless-stopped

  # Optional: Sample order service for testing
  order-service:
    image: nginx:alpine
    ports:
      - "8003:80"
    volumes:
      - ./sample_services/order_service.conf:/etc/nginx/conf.d/default.conf
      - ./sample_services/order_service:/usr/share/nginx/html
    restart: unless-stopped

volumes:
  redis_data:
